---
title: "Weather Data Dashboard (RNOAA)"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r plotly_library_setup, include = FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(dplyr)
library(rnoaa)
library(stringr)
```

```{r import_data, include = FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) |>
  select(name, id, everything())

weather_df = weather_df |> 
  drop_na() |> 
  mutate(
    tavg = (tmax + tmin) / 2,
    name_str = str_replace_all(name, c("CentralPark" = "Central Park", "_" = ", "))
    )
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
weather_df |> 
  plot_ly(x = ~month, y = ~tavg, color = ~name_str,
          type = "scatter", mode = "markers") |> 
  layout(
    title = "Average Daily Temperatures over Time",
    xaxis = list(title ="Date"), 
    yaxis = list(title = "Average Daily Temperature (°C)")
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
weather_df |> 
  filter(year(month) == 2022) |> 
  mutate(
    month_name = as.factor(substr(month.name[month(month)], 1, 3)),
    month_name = fct_reorder(month_name, month(month))
    ) |> 
  plot_ly(x = ~month_name, y = ~tavg, color = ~month_name,
          type = "box", colors = "viridis") |> 
  layout(
    title = "Temperature Distrubution for each Month in 2022",
    xaxis = list(title ="Month"), 
    yaxis = list(title = "Average Daily Temperature (°C)")
  )
```

### Chart C

```{r}
weather_df |> 
  drop_na() |> 
  filter(name == "Waterhole_WA", !(date %in% c(as.Date("2022-04-05"), as.Date("2022-12-26")))) |> 
  mutate(date = fct_reorder(as.factor(date), prcp)) |> 
  arrange(-prcp) |> 
  head(10) |> 
  plot_ly(x = ~date, y = ~prcp, type = "bar", color = ~name_str) |> 
  layout(
    title = "The 10 Rainiest Days in Waterhole, WA",
    xaxis = list(title ="Date"), 
    yaxis = list(title = "Precipitation (cm)")
  )
```





